### ISSUE TITLE
HACKccessibility: expose the documentation that lives in the developer's head

### ISSUE THREAD

**Issue by jibe-b** [mozilla/global-sprint#149]
**[ Project Contact ]** @jibe-b
**[ GitHub Repo ]** http://github.com/jibe-b/HACKccessibility-expose-the-documentation
**[ Track ]** Openness, 
**[ Location ]** Paris, France, UCT+01:00

### Description
Documentation requires a lot of human energy.

Tons of programs are fully featured and yet little documented.

An HACKccessibility wizard will help developers to document undocumented code and a webapp populated by data from an analysis of git repositories will provide insight on pieces of code with regards to their documentation and code patterns. A set of free software projects exposing little documentation will be contacted and proposed to use the wizard for documentation sprints. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by jibe-b** [comment]
This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Hey @jibe-b!

This looks great - I've approved your listing on Mozilla Pulse 🎉 : https://www.mozillapulse.org/entry/612

Also, it's great to a gitlab project here! Since we link to the [mozsprint label on issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Amozsprint+archived%3Afalse+), it might help the visibility of your project if you create a few issues in your github repo (like you have in gitlab!) and add the `mozsprint` label. Nice work 👍 😄
