### ISSUE TITLE
#Rethink Web Literacy

### ISSUE THREAD

**Issue by omudongo** [mozilla/global-sprint#232]
**[ Project Contact ]** @omudongo
**[ GitHub Repo ]** https://github.com/omudongo/-Rethink-Web-Literacy
**[ Track ]** Web Literacy, 
**[ Location ]** Cambridge, UK GMT+1
**[ Coach ]** Your OL5 Mentor

### Description
#Rethink Web Literacy project seeks to dymistify, thought challenges and  implement  various dynamics to teaching Web literacy through research, collaboration and community building. Additionally, the work of this project targets and engages with next generation leaders, identifying their passion, strengths and their capability to revolutionize their communities while creating a lasting change that bridges their societies digital divides. 
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by omudongo** [comment]
This is ready to be featured on Mozilla Pulse @acabunoc or @zee-moz

**Comment by abbycabs** [comment]
HI @omudongo -- I can't find your project in Mozilla Pulse. Did you follow all the instructions here: https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/

**Comment by omudongo** [comment]
Hey! @acabunoc  am on it right now, few things I noticed. I'll keep you in the loop.

**Comment by abbycabs** [comment]
Hi @omudongo I'd love to feature your project. Any update on submitting your project to pulse? https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/

**Comment by omudongo** [comment]
@acabunoc Yeah! sure please do I've just submitted my request and i'd be glad to hear from you soon after review.

**Comment by zee-moz** [comment]
Hi @omudongo just a couple small things before we can feature your project:

- You have some place-holder text lingering in your README-- Under "contributing" there's a repeated sentence with [PROJECT] in brackets-- just go ahead and delete that 😄 
- In CONTRIBUTING.MD your link to the issue sends me to an Asana log-in page-- maybe for the Sprint, link to your local GH issues tab?
- Also in Contributing, your link to the Roadmap gives me a 404 Not Found error-- maybe just update that link?

And one bit of feedback-- for the issue you list asking for a  logo and website, I might break these tasks into two issues (or more), as building a website can be a big job-- bigger than what's possible at the Sprint.

Otherwise, looks good! Fix the 3 things in the list and we'll get this on Pulse.

**Comment by abbycabs** [comment]
Hey @omudongo 

You have two days left to get on the [featured projects page](https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/)! Check off the last few items and [submit your project to Pulse](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) by Wednesday to get featured 🎉 

Let us know if you have any questions! And happy sprinting :)

**Comment by omudongo** [comment]
@acabunoc and @zee-moz  I've addressed all issues mentioned. I had initially submitted my project to Pulse please check and let me know.

**Comment by Btayeg** [comment]
@omudongo let me know if there is anything I can help with!

**Comment by abbycabs** [comment]
Hi @omudongo - I left a pull request: https://github.com/omudongo/-Rethink-Web-Literacy/pull/5
But other than that, this is good for Pulse!
https://www.mozillapulse.org/entry/754
https://foundation.mozilla.org/opportunity/global-sprint/2018-projects/

**Comment by samitalks** [comment]
please let me know if theres any contribution i can make here

**Comment by jcmolloy** [comment]
See request for a logo design for the Funda project here if anyone on MozSprint is able to help out!
https://github.com/mozilla/OpenDesign/issues/210
