### ISSUE TITLE
Making Interacting Chat Bots in an hour

### ISSUE THREAD

**Issue by subhash-Dulla** [mozilla/global-sprint#247]
**[ Project Contact ]** @subhash-Dulla
**[ GitHub Repo ]** https://github.com/subhash-Dulla/Chatbots
**[ Track ]** Web Literacy, Internet Privacy, Digital Inclusion, 
**[ Location ]** Amalapuram and IST
**[ Coach ]** @princiya 
 
### Description
Chat Bots give users new ways to interact with your product by building engaging voice and text-based conversational interfaces powered by AI, we can build a chat bot using IBM Watson , Dialog Flow , Microsoft Azure ...By the end of my session the participants can Build and deploy their own chat bots. i have made a chat bot that can help my participants to register for the global sprint 2018 and to answer any query regarding GS-18.

***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by princiya** [comment]
@subhash-Dulla Thank you for your interest and participation. To confirm, please add your project repo here so that we get an initial idea too :)

**Comment by abbycabs** [comment]
Hi @subhash-Dulla & @princiya -- I've assigned @princiya as the coach to this since you're not currently in the mentorship program!

**Comment by abbycabs** [comment]
Hey @subhash-Dulla 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by subhash-Dulla** [comment]
hello @princiya

**Comment by princiya** [comment]
Hello @subhash-Dulla I see you have ticked off all the items from the checklist, but the link to your project is missing. Could you share it so that we can review before giving the green light?

From email conversation:

@subhash-Dulla 
> Hello,
Glad to know that you are assigned as couch for my project making interactive chatbots in an hour . i got a mail that i need to finish checklist by today otherwise issues will be closed.i need your help to know about how to work in github on the day of event and my project does not need github because we are not using a little code to build cahtbot.

@princiya
> Hi Dulla,
If you do not intend to use Github, then how do you plan to work with contributors? Could you write about this concern in your corresponding MozSprint issue in Github?
Regards,
Princiya

**Comment by subhash-Dulla** [comment]
Hi Princiya,
Thanks for your advise we are using github for sure, out of 50 participants
only 5 participants know to use github and only few attended the intro call
on Global sprint .so i would like to demonstrate on  how git and github
works..
Regards,
subhash

**Comment by princiya** [comment]
Ok @subhash-Dulla Can you share any link about your project?

**Comment by subhash-Dulla** [comment]
https://web.telegram.org/#/im?p=@Globalsprint_bot
this is a chatbot deployed in telegram ,it will answer quires regarding
global sprint.
https://bot.dialogflow.com/646961ef-db78-4725-9b25-a6f09b3bbc15
this is a demo bot deployed in ti.to website

**Comment by subhash-Dulla** [comment]
https://github.com/subhash-Dulla/Chatbots
this is my github repo

**Comment by subhash-Dulla** [comment]
tonight i am updating the slides that i have presented in the read me file
