### ISSUE TITLE
Open Maps

### ISSUE THREAD

**Issue by zbouslama** [mozilla/global-sprint#254]
**[ Project Contact ]** @zbouslama
**[ GitHub Repo ]** https://github.com/zbouslama/open_maps
**[ Track ]** Openness, 
**[ Location ]** Tunis, Africa, UTC+1
**[ Coach ]** @SamanthaHindle & @aariops

### Description
The aim of this project, is to offer an open, user friendly alternative to Geographic Information System (GIS) Softwares. It will be accessible to GIS and non GIS users and its use won't require any programming experience. Open maps will offer interactive visualization of scientific data projected on 2D maps. The application will be developed based on the use of open packages such as Python libraries.
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

***

## Note to the Project Lead :tada:
Congrats, @zbouslama! This is your official project listing for the Mozilla Global Sprint 2018. To confirm your registration, please complete and check off the following:

- [x] Complete [Open Leadership 101](https://mozilla.teachable.com/p/open-leadership-101)
- [x] Provide a GitHub repository for work and discussion on your project (in a comment or at the top of this issue)
- [x] [Create a README file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/) in your project repository. This file should help newcomers understand what your project is, why it's important, and kinds of help you're looking for.
- [x] [Create file: LICENSE](http://choosealicense.com/) to give your project an open license, allowing for sharing and remixing.
- [x] Turn on your [Issue Tracker](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) and create at least three issues to describe each task that you need help with and how a contributor can get started on that task.
- [x] [Create a label](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#5-add-a-mozsprint-label) called `mozsprint` and apply it to your issues.

#### Checklist for FEATURED Projects :clipboard:
To have your project FEATURED on [Mozilla Pulse](http://mozillapulse.org/), complete the following documentation. In past Sprints, well-documented featured projects have 5 times more contributions than other projects. Details about each item and more information about how to create them are [on our Project Requirements Page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/).

* [x] In your README, link to the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) or [write your own code of conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/).
* [x] Create file: CONTRIBUTING.md so others know how they can contribute. If you'd like, you can [remix this template](https://github.com/acabunoc/mozsprint-repo-template/blob/master/CONTRIBUTING.md)
* [x] [Follow these instructions](https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/) to submit your project to Mozilla Pulse.

Once all of the above is complete,
- [x] Leave a comment with the text `This is ready to be featured on Mozilla Pulse`. Your Project Coach  will review this issue and approve your project if everything looks good :balloon:

If you get stuck at any point, feel free to look at the [requirements page](https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/) and [project templates](https://mozilla.github.io/global-sprint/project-lead-guide/templates/) or reach out to your Project Coach, @SamanthaHindle & @aariops. We're here to help you through this process.

**Comment by abbycabs** [comment]
@aariops left great comments:
https://github.com/mozilla/global-sprint/issues/256#issuecomment-379854542

copied out below:

---
Hey @zbouslama,

Welcome to Mozilla's Global Sprint. Your project is starting to shape up well. 😄

I see you already created the Read Me file. I think it is quite well structured: it tells people what the project is, why it matters and the technology that is based on. Good job! Now, you need to pick a license for the repo and start writing issues.

The license is important so that people know what they can do with the code and how they can share new technology they developed based on Open Maps. For instance, since your project is targeted at low-income countries, maybe you want to ensure that people who use the technology share it under the same permissions to an extent, like the Mozilla Public License. There are many licenses available; this website can help you pick the right one for Open Maps.

Issues can be more or less complicated.They can be anything from "designing a logo" to "connect to a new hosting server". For users to find them. it's easier if you tag your issues with labels, such as "Python" "Design", etc. For Global Sprint, we encourage your to add the mozprint tag. It's also a good idea to add help wanted, to let other people know they can help out.

Let the fun begin! 💻

Let me or @SamanthaHindle know if you need any help. 👍

**Comment by SamanthaHindle** [comment]
Hi @zbouslama! 
Open Maps looks like a really useful tool and a great project for the Mozsprint! 
If you need any help with creating new issues or labels, check out this [link](https://mozilla.github.io/global-sprint/project-lead-guide/templates/#4-create-issues) as it's super useful, or ask a question here. We are happy to help!

**Comment by abbycabs** [comment]
Hey @zbouslama 

Thanks for submitting your project to #mozsprint!

You're almost done your registration. Please complete the first 6 items in the checklist 📝 
If these aren't completed by May 9th, we'll be closing this issue. Let us know if you have any questions! Happy Sprinting 🎉

**Comment by abbycabs** [comment]
Hi @zbouslama 

Since you haven't completed your registration and the Global Sprint has started, I'll be closing this issue. You're welcome to re-open this and join the Sprint if you find time to complete registration!

**Comment by zbouslama** [comment]
hi
happy to join you on mozsprint
3 people already working on 
Now, I completed registration
can you please re-open the project on mozsprint
thank you
zied
