### ISSUE TITLE
TPP

### ISSUE THREAD

**Issue by glaand** [mozilla/global-sprint#274]
**[ Project Contact ]** @tpportugal
**[ GitHub Repo ]** https://github.com/tpportugal
**[ Track ]** Openness, Digital Inclusion, 
**[ Location ]** Lisbon, PT - UTC + 1
**[ Coach ]** @aariops 

### Description
Project for informational unification of the public transport in Portugal
***

## Want to contribute to this project during #mozsprint?
Join us at the Global Sprint, May 10-11. Leave a comment below if you're interested in contributing to this project during #mozsprint 2018!

**Comment by glaand** [comment]
@aariops This is ready to be featured on Mozilla Pulse

**Comment by abbycabs** [comment]
Hey @glaand! I've listed these repos for your project:
https://github.com/repos/tpportugal/ficheiros_gtfs_sem_hospedeiro
https://github.com/repos/tpportugal/tpp
https://github.com/repos/tpportugal/tpp_admin
https://github.com/repos/tpportugal/tpp_app
https://github.com/repos/tpportugal/tpp_banco_de_dados
https://github.com/repos/tpportugal/tpp_expedidor
https://github.com/repos/tpportugal/tpp_explorador
https://github.com/repos/tpportugal/tpp_gtfs_lib
https://github.com/repos/tpportugal/tpp_registo_de_feeds
https://github.com/repos/tpportugal/tpp_routing_demo
https://github.com/repos/tpportugal/tpp_upload
https://github.com/repos/tpportugal/tpp_valhalla
https://github.com/repos/tpportugal/tpp_valhalla_api_docs
https://github.com/repos/tpportugal/tpp_website
https://github.com/repos/tpportugal/webserver

Let me know if I'm missing anything!

**Comment by glaand** [comment]
@acabunoc Thank you for listing all the repos!
We would like to include this one too: https://github.com/tpportugal/Nominatim
Thank you!

**Comment by aariops** [comment]
Hey @glaand 

Great job! 

Since there is no easy way to edit a Mozilla Pulse entry, the featured article will be missing the <2018> tag. It's not ideal, but you can refill the submission form (sorry!). 

If you're doing so, I'd suggest adding a little description to the "Get Involved" part. It usually lets people feel more welcome. :smile: You can also list your priorities in terms of the help you're hoping to get during the sprint.

Let me know what you decide, so I can approve the current submission, or wait for the new one.

Cheers

**Comment by aariops** [comment]
https://www.mozillapulse.org/entry/791 it's now live on Pulse! :smile:
